<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>subprocess on tanaike</title>
    <link>https://tanaikech.github.io/tags/subprocess/</link>
    <description>Recent content in subprocess on tanaike</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>ja</language>
    <copyright>&amp;copy; 2017. All rights reserved.</copyright>
    <lastBuildDate>Fri, 09 Jun 2017 14:27:19 +0900</lastBuildDate><atom:link href="https://tanaikech.github.io/tags/subprocess/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>Error Handling for Subprocess at Python</title>
      <link>https://tanaikech.github.io/2017/06/09/error-handling-for-subprocess-at-python/</link>
      <pubDate>Fri, 09 Jun 2017 14:27:19 +0900</pubDate>
      
      <guid>https://tanaikech.github.io/2017/06/09/error-handling-for-subprocess-at-python/</guid>
      <description>This sample is for error handling for subprocess.Popen. It confirms whether the execution file is existing. If the execution file is also not in the path, the error message is shown.
import subprocess res = subprocess.Popen( &amp;#34;application&amp;#34;, # &amp;lt;- Execution file stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True ).communicate() if len(res[1]) == 0: print(&amp;#34;ok: Application is existing.&amp;#34;) else: print(&amp;#34;Error: Application is not found.&amp;#34;) </description>
    </item>
    
  </channel>
</rss>
